version: '3'

services:
  graphql:
    build: .
    ports:
    - 3000:3000
    volumes:
      - .:/app:z
      - /app/node_modules
    environment:
      - DATABASE_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/test

  mongodb:
    image : mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
